declare type EnvironmentVariables = {
  YOUTUBE_API_KEY: string;
  PROXY_HOST: string;
  PROXY_PORT: string;
  PROXY_USERNAME: string;
  PROXY_PASSWORD: string;
  PROXY_HOST_2: string;
  PROXY_PORT_2: string;
  PROXY_USERNAME_2: string;
  PROXY_PASSWORD_2: string;
  TWITTER_BEARER_TOKEN: string;
  TWITTER_API_KEY: string;
  TWITTER_API_SECRET_KET: string;
  TWITTER_ACCESS_TOKEN: string;
  TWITTER_ACCESS_TOKEN_SECRET: string;
  TWITTER_USERNAME: string;
  TWITTER_PASSWORD: string;
  INSTAGRAM_USERNAME: string;
  INSTAGRAM_PASSWORD: string;
  SENTRY_DSN: string;
  SENTRY_ENV: string;
  SCHEDULE_ENABLED: string;
};
