declare type EnvironmentVariables = {
  DB_HOST: string;
  DB_PORT: number;
  DB_USERNAME: string;
  DB_PASSWORD: string;
  DB_NAME: string;
  DB_SOCKET_PATH?: string;
  YOUTUBE_API_KEY: string;
  PROXY_HOST: string;
  PROXY_PORT: string;
  PROXY_USERNAME: string;
  PROXY_PASSWORD: string;
  PROXY_HOST_2: string;
  PROXY_PORT_2: string;
  PROXY_USERNAME_2: string;
  PROXY_PASSWORD_2: string;
  TWITTER_BEARER_TOKEN: string;
  INSTAGRAM_USERNAME: string;
  INSTAGRAM_PASSWORD: string;
};
